server:
  port: 8711
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raghava238/configserverproperties.git
          refresh-rate: 1

zipkin:
  base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,metrics,prometheus

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_BASE_URL:http://localhost:8712/eureka/}
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
